### ISSUE TITLE
Link Error on Ubuntu 14.04

### ISSUE THREAD

**Issue by samuelkgutierrez** [LLNL/LaunchMON#1]
Hi,

I'm trying to configure and build LaunchMON on a pretty vanilla Ubuntu 14.04 box and I'm seeing the following link error during the build.

In the following directory: LaunchMON/tools/libgcrypt/tests

/bin/bash ../libtool --mode=link gcc -I/home/samuel/local/STAT/include -I/home/samuel/src/LaunchMON/tools/libgpg-error/src -g -O2 -Wall   -o basic  basic.o ../src/libgcrypt.la -lnsl  -lnsl
gcc -I/home/samuel/local/STAT/include -I/home/samuel/src/LaunchMON/tools/libgpg-error/src -g -O2 -Wall -o .libs/basic basic.o  ../src/.libs/libgcrypt.so -lnsl -Wl,--rpath -Wl,/home/samuel/local/STAT/lib
/usr/bin/ld: basic.o: undefined reference to symbol 'gpg_strerror'
/home/samuel/local/STAT/lib/libgpg-error.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

It seems as if a missing -lgpg-error is causing this problem. When I manually link, things seem to work fine.

$ gcc -I/home/samuel/local/STAT/include -I/home/samuel/src/LaunchMON/tools/libgpg-error/src -g -O2 -Wall -o .libs/basic basic.o  ../src/.libs/libgcrypt.so -lnsl -Wl,--rpath -Wl,/home/samuel/local/STAT/lib -lgpg-error

Thanks,

Sam

**Comment by buaaluwentao** [comment]
Hi
recent ,I was  building  launchmon ,I got error like you when I run make ,my launchmon version is launchmon-1.0-release and os is x86-64-ubuntu.
I want to know how should i modify my Makefile to make it work fine because I link it manually like this "gcc -I ../STAT/include -I ./tools/libgpg-error/src -g -O2 -Wall -o .libs/basic basic.o /usr/lib/i386-linux-gnu/libgcrypt.so  -lnsl -Wl,--rpath -Wl,../STAT/lib -lgpg-error
" i got new error like "gcc: error: basic.o: 没有那个文件或目录",can anyone help me,thanks.

**Comment by dongahn** [comment]
@buaaluwentao: hmmm. this should have been fixed. Did you install all of the dependent packages including gpg-error? We no longer include gcrypt and gpg-error packages into the release (nor the source tree) as this created dependency management issues.
